### ISSUE TITLE
Possible SQL injection point?

### ISSUE THREAD

**Issue by SKKUGoon** [HerodotusDev/L2-indexer#1]
https://github.com/HerodotusDev/opstack_indexer/blob/a058388150d7a75cb5cc4bc66057e2caf3d53714/crates/monitor_events/src/main.rs#L61C28-L61C28

Do not parse strings directly into your sql query. Prone to SQL injection attacks. 

Recommend using ORMs

**Comment by beeinger** [comment]
Removed the SQL injection vulnerability here: https://github.com/HerodotusDev/L2-indexer/commit/38f46901d9668a99575ddcc5e531224bc123341d

Didn't add an ORM yet, but all possible input from user is going through validation, and there is no possibility for SQL injection.
